import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap/dist/js/bootstrap.bundle.min.js";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "swiper/swiper-bundle.css";
import "animate.css/animate.min.css";
import "owl.carousel/dist/assets/owl.carousel.css";
import './NikkiDodgePhotography.css';
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Home from "./pages/Home";
import Users from "./pages/Users";
import Pricing, { PRICING } from "./pages/Pricing";
import Portfolio, { PORTFOLIO } from "./pages/Portfolio";
import Contact, { CONTACT } from "./pages/Contact";
import Howdy, { HOWDY } from "./pages/Howdy";
import Blog, { BLOG } from "./pages/Blog";
import Gallery, { GALLERY } from "./pages/Gallery";
const NikkiDodgePhotography = () => {
    return (_jsxs(Router, { children: [_jsx(Header, {}), _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(Home, {}) }), _jsx(Route, { path: PRICING, element: _jsx(Pricing, {}) }), _jsx(Route, { path: PORTFOLIO, element: _jsx(Portfolio, {}) }), _jsx(Route, { path: PORTFOLIO + "/:categoryName", element: _jsx(Portfolio, {}) }), _jsx(Route, { path: PORTFOLIO + "/:categoryName/:search", element: _jsx(Portfolio, {}) }), _jsx(Route, { path: "/Users", element: _jsx(Users, {}) }), _jsx(Route, { path: CONTACT, element: _jsx(Contact, {}) }), _jsx(Route, { path: HOWDY, element: _jsx(Howdy, {}) }), _jsx(Route, { path: BLOG, element: _jsx(Blog, {}) }), _jsx(Route, { path: GALLERY + "/:categoryName/:sessionName", element: _jsx(Gallery, {}) })] }), _jsx(Footer, {})] }));
};
export default NikkiDodgePhotography;
